---
format: acm-pdf

# use keep-tex to cause quarto to generate a .tex file
# which you can eventually use with TAPS
keep-tex: true

bibliography: bibliography.bib

title: Reproduction of Hanabi AI

# if short-title is defined, then it's used
short-title: Hope

author:
  - name: MJ Johns
    email: mljohns@ucsc.edu
    orcid: 0009-0002-4016-2517    
    affiliation:
      name: University of California Santa Cruz
      country: USA
  - name: Adam
    email: 
    affiliation:
      name: University of California Santa Cruz
      country: USA
  - name: Markus
    affiliation:
      name: University of California Santa Cruz
      country: USA
    email: 


# acm-specific metadata
acm-metadata:
  # comment this out to make submission anonymous
  # anonymous: true

  # comment this out to build a draft version
  final: true

  # comment this out to specify detailed document options
  # acmart-options: sigconf, review  

  # acm preamble information
  copyright-year: 2018
  acm-year: 2018
  copyright: acmcopyright
  doi: XXXXXXX.XXXXXXX
  conference-acronym: "Conference acronym 'XX"
  conference-name: |
    Make sure to enter the correct
    conference title from your rights confirmation
  conference-date: June 03--05, 2018
  conference-location: Woodstock, NY
  price: "15.00"
  isbn: 978-1-4503-XXXX-X/18/06

  # if present, replaces the list of authors in the page header.
  shortauthors: Johns et al.

  # The code below is generated by the tool at http://dl.acm.org/ccs.cfm.
  # Please copy and paste the code instead of the example below.
  ccs: |
    \begin{CCSXML}
    <ccs2012>
     <concept>
      <concept_id>10010520.10010553.10010562</concept_id>
      <concept_desc>Computer systems organization~Embedded systems</concept_desc>
      <concept_significance>500</concept_significance>
     </concept>
     <concept>
      <concept_id>10010520.10010575.10010755</concept_id>
      <concept_desc>Computer systems organization~Redundancy</concept_desc>
      <concept_significance>300</concept_significance>
     </concept>
     <concept>
      <concept_id>10010520.10010553.10010554</concept_id>
      <concept_desc>Computer systems organization~Robotics</concept_desc>
      <concept_significance>100</concept_significance>
     </concept>
     <concept>
      <concept_id>10003033.10003083.10003095</concept_id>
      <concept_desc>Networks~Network reliability</concept_desc>
      <concept_significance>100</concept_significance>
     </concept>
    </ccs2012>
    \end{CCSXML}
    
    \ccsdesc[500]{Computer systems organization~Embedded systems}
    \ccsdesc[300]{Computer systems organization~Redundancy}
    \ccsdesc{Computer systems organization~Robotics}
    \ccsdesc[100]{Networks~Network reliability}

  keywords:
    - datasets
    - neural networks
    - gaze detection
    - text tagging
  
  # if uncommented, this produces a teaser figure
  # 
  # teaser:
  #   image: sampleteaser
  #   caption: figure caption
  #   description: teaser description    

abstract: |
  Reproduction and extension of an exploratory analysis of different implementations of a game-playing AI for the board game Hanabi. The original paper examined three implementations: a baseline called 'Outer' which has been used in past implementations, an intentional AI (called Intentional), and an AI which combines the two (called 'Full'). The authors of the original paper found that the Intentional AI outperformed the other two implementations when paired with a human player. Here we reproduce their results and extend our analysis to consider whether player perception of AI skill, intentionality, or likeability may have influenced the score, regardless of implementation. We also perform Machine Learning on the game logs and propose an update to the AI framework to include predictive modeling of player behavior. 
---

# Introduction

Template: ACM's consolidated article template, introduced in 2017, provides a consistent \LaTeX style for use across ACM publications, and incorporates accessibility and metadata-extraction functionality necessary for future Digital Library endeavors. Numerous ACM and SIG-specific \LaTeX templates have been examined, and their unique features incorporated into this single new template.

Our introduction...

# Exploratory Data Analysis

Discuss our EDA methods...

ANOVA / Tukey

# Methods

Study description

Quantitative Analysis

# Results

What do we find...our reproduction supports the original author's conclusion about the Intentional AI

# Discussion and Conclusion

We conclude that...

-   

The ACM Reference Format text is required for all articles over one page in length, and is optional for one-page articles (abstracts).

# CCS Concepts and User-Defined Keywords

The ACM Computing Classification System --- <https://www.acm.org/publications/class-2012> --- is a set of classifiers and concepts that describe the computing discipline. Authors can select entries from this classification system, via <https://dl.acm.org/ccs/ccs.cfm>, and generate the commands to be included in the \LaTeX source.

# Tables

The "`acmart`" document class includes the "`booktabs`" package --- <https://ctan.org/pkg/booktabs> --- for preparing high-quality tables.

Table captions are placed *above* the table.

Because tables cannot be split across pages, the best placement for them is typically the top of the page nearest their initial cite. To ensure this proper "floating" placement of tables, use the environment **table** to enclose the table's contents and the table caption. The contents of the table itself must go in the **tabular** environment, to be aligned properly in rows and columns, with the desired horizontal and vertical rules. Again, detailed instructions on **tabular** material are found in the \LaTeX User's Guide.

Immediately following this sentence is the point at which @tbl-freq is included in the input file; compare the placement of the table here with the table in the printed output of this document.

| Non-English or Math |  Frequency  | Comments          |
|:-------------------:|:-----------:|:------------------|
|          Ø          | 1 in 1,000  | For Swedish names |
|        $\pi$        |   1 in 5    | Common in math    |
|         \$          |   4 in 5    | Used in business  |
|     $\Psi^2_1$      | 1 in 40,000 | Unexplained usage |

: Frequency of Special Characters {#tbl-freq}

# Math Equations

You may want to display math equations in three distinct styles: inline, numbered or non-numbered display. Each of the three are discussed in the next sections.

## Inline (In-text) Equations

A formula that appears in the running text is called an inline or in-text formula. It is produced by the **math** environment, which can be invoked with the usual `\begin, ... \end` construction or with the short form `\$ ... \$`. You can use any of the symbols and structures, from $\alpha$ to $\omega$, available in \LaTeX[@Lamport:LaTeX]; this section will simply show a few examples of in-text equations in context. Notice how this equation: $\lim_{n\rightarrow \infty}x=0$, set here in in-line math style, looks slightly different when set in display style. (See next section).

## Display Equations

A numbered display equation---one set off by vertical space from the text and centered horizontally---is produced by the \textbf{equation} environment. An unnumbered display equation is produced by the **displaymath** environment.

Again, in either environment, you can use any of the symbols and structures available in \LaTeX\@; this section will just give a couple of examples of display equations in context. First, consider @eq-oneequation, shown as an inline equation above:

$$
\lim_{n\rightarrow \infty}x=0
$$ {#eq-oneequation}

Notice how it is formatted somewhat differently in the **displaymath** environment. Now, we'll enter an unnumbered equation:

$$\sum_{i=0}^{\infty} x + 1$$

and follow it with @eq-anotherequation, another numbered equation:

$$
\sum_{i=0}^{\infty}x_i=\int_{0}^{\pi+2} f
$$ {#eq-anotherequation}

just to demonstrate \LaTeX's able handling of numbering.

# Figures

The "`figure`" environment should be used for figures. One or more images can be placed within a figure. If your figure contains third-party material, you must clearly identify it as such, as shown in the example below.

![1907 Franklin Model D roadster. Photograph by Harris & Ewing, Inc. \[Public domain\], via Wikimedia Commons. (<https://goo.gl/VLCRBB>).](sample-franklin.png){#fig-dresses fig-alt="A woman and a girl in white dresses sit in an open car."}

Your figures should contain a caption which describes the figure to the reader.

Figure captions are placed *below* the figure.

Every figure should also have a figure description unless it is purely decorative. These descriptions convey what’s in the image to someone who cannot see it. They are also used by search engine crawlers for indexing images, and when images cannot be loaded.

# Citations and Bibliographies

The use of \BibTeX for the preparation and formatting of one's references is strongly recommended. Authors' names should be complete --- use full first names ("Donald E. Knuth") not initials ("D. E. Knuth") --- and the salient identifying features of a reference should be included: title, year, volume, number, pages, article DOI, etc.

The bibliography is included in your source document with these two commands, placed just before the \\verb\|\\end{document}\| command:

```         
  \bibliographystyle{ACM-Reference-Format}
  \bibliography{bibfile}
```

where "`bibfile`" is the name, without the "`.bib`" suffix, of the \BibTeX file.

Citations and references are numbered by default. A small number of ACM publications have citations and references formatted in the "author year" style; for these exceptions, please include this command in the **preamble** (before the command "`\begin{document}`") of your \LaTeX source:

```         
  \citestyle{acmauthoryear}
```

Some examples. A paginated journal article [@Abril07], an enumerated journal article [@Cohen07], a reference to an entire issue [@JCohen96], a monograph (whole book) [@Kosiur01], a monograph/whole book in a series (see 2a in spec. document) [@Harel79], a divisible-book such as an anthology or compilation [@Editor00] followed by the same example, however we only output the series if the volume number is given [@Editor00a] (so Editor00a's series should NOT be present since it has no vol. no.), a chapter in a divisible book [@Spector90], a chapter in a divisible book in a series [@Douglass98], a multi-volume work as book [@Knuth97], a couple of articles in a proceedings (of a conference, symposium, workshop for example) (paginated proceedings article) [@Andler79, @Hagerup1993], a proceedings article with all possible elements [@Smith10], an example of an enumerated proceedings article [@VanGundy07], an informally published work [@Harel78], a couple of preprints [@Bornmann2019, @AnzarootPBM14], a doctoral dissertation [@Clarkson85], a master's thesis: [@anisi03], an online document / world wide web resource [@Thornburg01, @Ablamowicz07, @Poker06], a video game (Case 1) [@Obama08] and (Case 2)[@Novak03] and [@Lee05] and (Case 3) a patent [@JoeScientist001], work accepted for publication [@rous08], 'YYYYb'-test for prolific author [@SaeediMEJ10] and [@SaeediJETC10]. Other cites might contain 'duplicate' DOI and URLs (some SIAM articles) [@Kirschmer-2010-AEI-1958016-1958018]. Boris / Barbara Beeton: multi-volume works as books [@MR781536] and [@MR781537]. A couple of citations with DOIs: [@2004-ITE-1009386-1010128, @Kirschmer-2010-AEI-1958016-1958018]. Online citations: [@TUGInstmem, @Thornburg01, @CTANacmart]. Artifacts: [@R] and [@UMassCitations].

# Acknowledgments

Identification of funding sources and other support, and thanks to individuals and groups that assisted in the research and the preparation of the work should be included in an acknowledgment section, which is placed just before the reference section in your document.

This section has a special environment:

```         
  \begin{acks}
  ...
  \end{acks}
```

so that the information contained therein can be more easily collected during the article metadata extraction phase, and to ensure consistency in the spelling of the section heading.

Authors should not prepare this section as a numbered or unnumbered `\section`; please the "`\acks`" environment.